name: "E2E Tests - Cypress"
on:
  push:
    branches: [ main ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci --prefix frontend
      - run: npm start --prefix frontend &
      - uses: jakejarvis/wait-action@v0.1.3
        with:
          timeout: '60'
          url: 'http://localhost:3000'
      - run: npm run cy:run