name: Full Stack CI

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'app/**'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'app/**'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: irttx
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install backend requirements
      run: |
        pip install -r requirements.txt

    - name: Run backend tests
      run: |
        pytest tests/
